# Gathering Data
The first stage of this project is to gather 3 different sources of data:
- Manually download Twitter Archived Enhanced CSV file and read in data
- Download programatically Image Predictions TSV file from web server and read in data
- Use Twitter API to gather 'Likes' and 'Retweet' data for each tweet

#### Manually download Twitter Archived Enhanced CSV file and read in data
This was fairly straightforward, and only required the use of pandas to read in the the manually downlaoded csv file, which was then stored in a dataframe.

In [6]:
import pandas as pd

In [7]:
df_twitter_archive = pd.read_csv("twitter-archive-enhanced.csv")

In [8]:
# check data read in correctly
df_twitter_archive.head()

,tweet_id,in_reply_to_status_id,in_reply_to_user_id,timestamp,source,text,retweeted_status_id,retweeted_status_user_id,retweeted_status_timestamp,expanded_urls,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo
0,892420643555336193,NaN,NaN,2017-08-01 16:23:56 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Phineas. He's a mystical boy. Only eve...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/892420643...,13,10,Phineas,None,None,None,None
1,892177421306343426,NaN,NaN,2017-08-01 00:17:27 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Tilly. She's just checking pup on you....,NaN,NaN,NaN,https://twitter.com/dog_rates/status/892177421...,13,10,Tilly,None,None,None,None
2,891815181378084864,NaN,NaN,2017-07-31 00:18:03 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Archie. He is a rare Norwegian Pouncin...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891815181...,12,10,Archie,None,None,None,None
3,891689557279858688,NaN,NaN,2017-07-30 15:58:51 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Darla. She commenced a snooze mid meal...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891689557...,13,10,Darla,None,None,None,None
4,891327558926688256,NaN,NaN,2017-07-29 16:00:24 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Franklin. He would like you to stop ca...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891327558...,12,10,Franklin,None,None,None,None

#### Download programatically Image Predictions TSV file from web server and read in data
To download this data I used the requests library as shown below:

In [9]:
# access and dpownload file
import requests 
url = r"https://d17h27t6h515a5.cloudfront.net/topher/2017/August/599fd2ad_image-predictions/image-predictions.tsv"
response = requests.get(url)

In [12]:
# write to file
with open("Image_Predictions.tsv", "wb") as file:
    file.write(response.content)

In [13]:
# read data into dataframe
df_image_predictions = pd.read_csv("Image_Predictions.tsv", sep = "\t")

In [14]:
# check data read in correctly
df_image_predictions.head()

,tweet_id,jpg_url,img_num,p1,p1_conf,p1_dog,p2,p2_conf,p2_dog,p3,p3_conf,p3_dog
0,666020888022790149,https://pbs.twimg.com/media/CT4udn0WwAA0aMy.jpg,1,Welsh_springer_spaniel,0.465074,True,collie,0.156665,True,Shetland_sheepdog,0.061428,True
1,666029285002620928,https://pbs.twimg.com/media/CT42GRgUYAA5iDo.jpg,1,redbone,0.506826,True,miniature_pinscher,0.074192,True,Rhodesian_ridgeback,0.072010,True
2,666033412701032449,https://pbs.twimg.com/media/CT4521TWwAEvMyu.jpg,1,German_shepherd,0.596461,True,malinois,0.138584,True,bloodhound,0.116197,True
3,666044226329800704,https://pbs.twimg.com/media/CT5Dr8HUEAA-lEu.jpg,1,Rhodesian_ridgeback,0.408143,True,redbone,0.360687,True,miniature_pinscher,0.222752,True
4,666049248165822465,https://pbs.twimg.com/media/CT5IQmsXIAAKY4A.jpg,1,miniature_pinscher,0.560311,True,Rottweiler,0.243682,True,Doberman,0.154629,True

#### Use Twitter API to gather 'Likes' and 'Retweet' data for each tweet
To gather this data I used the Python library Tweepy to access the Twitter API.

The Twitter API required authorisation before it could be used.
As such, I had to create a Twitter account and apply for a developer account.
Once my application for this was approved, I was able to generate the Consumer API keys, the Access Token and the Access Token Secret that were required for authorisation.

Please note that I have removed these tokens before submitting this report.

In [38]:
import tweepy

consumer_key = ''
consumer_secret = ''
access_token = ''
access_secret = ''

auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_secret)

api = tweepy.API(auth, wait_on_rate_limit=True)

To confirm the connection with the API was working correctly I ran this code below to retrieve data from the home timeline tweets.

In [47]:
# check API is working
public_tweets = api.home_timeline()
for tweet in public_tweets:
    print(tweet.text)
    break

Police urge people to be vigilant following 5,000 spiking reports last year.
https://t.co/OAsgegI57G

In [48]:
# determine tweet_ids to iterate over
tweet_ids = df_twitter_archive["tweet_id"].copy()
tweet_ids.head()

0    892420643555336193
1    892177421306343426
2    891815181378084864
3    891689557279858688
4    891327558926688256
Name: tweet_id, dtype: int64

In [56]:
import json
import time as time


deleted_tweet_ids = []

with open("tweet_json.txt","w") as file:
    
    for tweet_id in tweet_ids:
        
        start = time.time()
        
        try:
            
            # get tweet data
            tweet_data = api.get_status(tweet_id, tweet_mode="extended")
            
            # get tweet data as json
            tweet_json = tweet_data._json 
            
            # output json to file, then add new line to file
            json.dump(tweet_json, file)
            file.write("\n")
            
        except:
            
            # if tweet_id is missing append to list of deleted tweets
            print(str(tweet_id) + " not found")
            deleted_tweet_ids.append(tweet_id)
            
        end = time.time()
        print(end - start)

0.24831533432006836
1.3045711517333984
0.23944568634033203
0.21577191352844238
0.24812078475952148
0.24793457984924316
0.23248863220214844
0.2511136531829834
0.27791881561279297
0.22288846969604492
0.22980594635009766
0.25451111793518066
0.24520492553710938
0.26923584938049316
0.23783540725708008
1.3845624923706055
0.23429608345031738
0.2248241901397705
0.20174288749694824
888202515573088257 not found
0.23749542236328125
0.2372603416442871
0.19213032722473145
0.2477428913116455
0.2295701503753662
0.24902558326721191
0.22226691246032715
0.21996712684631348
0.22659659385681152
0.23643970489501953
0.46892547607421875
0.2328779697418213
0.21658968925476074
0.2337338924407959
0.2688405513763428
0.2305736541748047
0.20100855827331543
0.23619914054870605
0.23642778396606445
0.2443234920501709
0.23083138465881348
0.21916460990905762
0.21476435661315918
0.2322068214416504
0.24807381629943848
0.22268152236938477
0.22696924209594727
0.26369428634643555
1.1732285022735596
1.3003208637237549
0.26456260681152344
1.3671250343322754
0.24689841270446777
0.26689982414245605
1.3402893543243408
0.286712646484375
2.8539702892303467
0.24428606033325195
1.8022212982177734
0.23669695854187012
0.2409803867340088
1.3588149547576904
0.2525777816772461
0.24829316139221191
0.5052685737609863
0.2231006622314453
0.21525955200195312
0.22010326385498047
0.22184491157531738
0.2706940174102783
0.24045825004577637
0.22985100746154785
0.22402095794677734
0.23994231224060059
0.24474883079528809
0.21975064277648926
0.23057246208190918
0.4250614643096924
0.26626038551330566
877611172832227328 not found
0.194960355758667
0.2529733180999756
0.24943280220031738
0.23832178115844727
0.23915624618530273
0.26694321632385254
0.2248845100402832
0.20176172256469727
0.2149653434753418
0.2605764865875244
0.24011826515197754
0.24069428443908691
0.1980266571044922
0.2514762878417969
0.25186824798583984
0.2221388816833496
0.23191285133361816
873697596434513921 not found
0.22970962524414062
5.423609018325806
0.2971928119659424
0.22407293319702148
0.23386240005493164
0.22794628143310547
872668790621863937 not found
0.1934823989868164
0.24632668495178223
0.23964667320251465
872261713294495745 not found
0.23163747787475586
0.25647783279418945
0.24223661422729492
0.23984837532043457
0.24311184883117676
0.22356843948364258
0.296337366104126
0.2572650909423828
0.22163081169128418
0.1947629451751709
0.25740623474121094
0.2392871379852295
0.21359705924987793
0.24213480949401855
869988702071779329 not found
0.17653250694274902
0.21314120292663574
0.23167157173156738
0.21750092506408691
0.22152233123779297
0.22540521621704102
0.24165010452270508
0.23047494888305664
0.20790338516235352
0.23010635375976562
0.2250816822052002
0.24179768562316895
0.23441505432128906
0.2255403995513916
866816280283807744 not found
0.18005919456481934
0.23155903816223145
0.20161652565002441
0.22881317138671875
0.23892426490783691
0.23253798484802246
0.22547006607055664
0.22527050971984863
0.23490333557128906
0.2431046962738037
0.21331000328063965
0.2361621856689453
0.22927045822143555
0.2552461624145508
0.2528965473175049
0.19880104064941406
0.2360846996307373
0.2258777618408203
0.22745776176452637
0.22275352478027344
0.2380063533782959
0.22843408584594727
0.21049976348876953
861769973181624320 not found
0.19979119300842285
0.20893526077270508
0.23519659042358398
0.2177567481994629
0.21775197982788086
0.2463243007659912
0.23660683631896973
0.22687745094299316
0.222686767578125
0.20317554473876953
0.24923229217529297
0.234846830368042
0.22139596939086914
0.24144339561462402
0.22974729537963867
0.21805953979492188
0.25182318687438965
0.2216041088104248
0.21679902076721191
0.21985840797424316
0.22995591163635254
0.2441098690032959
0.23883390426635742
1.279355525970459
0.23325705528259277
0.24314403533935547
0.2441091537475586
856602993587888130 not found
0.18786954879760742
0.25040411949157715
0.23621845245361328
856330835276025856 not found
0.20034408569335938
0.21477603912353516
0.20619893074035645
0.22498679161071777
0.21300935745239258
0.46601319313049316
0.21220135688781738
0.2464308738708496
0.2700643539428711
0.2354273796081543
0.2108778953552246
0.20508623123168945
0.22767138481140137
0.21746063232421875
0.24282264709472656
0.19432973861694336
0.23716235160827637
0.3265221118927002
0.24744391441345215
0.23538970947265625
0.2828943729400635
0.256711483001709
0.23645925521850586
0.2748267650604248
0.2172255516052246
0.2363882064819336
851953902622658560 not found
0.18236470222473145
851861385021730816 not found
0.267960786819458
0.2552824020385742
0.2402956485748291
0.2335524559020996
0.1938786506652832
0.29236626625061035
0.222930908203125
0.22764945030212402
0.23191022872924805
0.22452354431152344
0.22153162956237793
0.21795058250427246
0.2402806282043457
0.27493786811828613
0.20761919021606445
0.23317837715148926
0.22140836715698242
0.22704815864562988
0.22118425369262695
0.24038410186767578
0.22410345077514648
4.874934196472168
0.23598980903625488
0.2379007339477539
0.23029208183288574
0.2092900276184082
0.23672795295715332
0.2342214584350586
1.3271448612213135
0.2565152645111084
0.77242112159729
0.7743079662322998
1.4003376960754395
1.348144292831421
0.20451045036315918
845459076796616705 not found
0.4804954528808594
1.0451815128326416
0.8564608097076416
0.6524558067321777
0.26193952560424805
0.2397780418395996
844704788403113984 not found
1.3710532188415527
0.49860453605651855
0.24042201042175293
0.2281041145324707
0.23795175552368164
0.25685739517211914
0.22778058052062988
842892208864923648 not found
0.24034643173217773
1.2497432231903076
0.25093960762023926
0.22341179847717285
0.21608233451843262
0.2263636589050293
0.24514484405517578
0.2497119903564453
0.23203182220458984
0.25600242614746094
0.2583155632019043
0.22798609733581543
0.2671639919281006
0.2537980079650879
0.23414230346679688
0.23446989059448242
0.22129034996032715
0.2793235778808594
0.2560570240020752
0.22684764862060547
0.270784854888916
839290600511926273 not found
0.19003939628601074
0.24067211151123047
0.2404930591583252
0.2153339385986328
0.21690821647644043
0.22333002090454102
0.20291447639465332
0.24273061752319336
0.2225511074066162
0.20604372024536133
0.23978328704833984
1.3820600509643555
0.23875975608825684
0.2326369285583496
0.25609874725341797
837366284874571778 not found
3.1623549461364746
0.8168115615844727
837012587749474308 not found
0.7530536651611328
0.7571799755096436
0.7469160556793213
1.2869725227355957
0.31428074836730957
1.3824903964996338
0.2700047492980957
0.23688220977783203
0.3949010372161865
0.25829005241394043
1.3527696132659912
0.7455780506134033
0.7459170818328857
1.307347059249878
0.2397327423095703
1.396585464477539
0.23185253143310547
1.3588752746582031
1.4902615547180176
0.23039841651916504
0.2307584285736084
0.7690222263336182
0.7564206123352051
0.24521708488464355
0.22968411445617676
0.45844173431396484
1.1045856475830078
1.473315954208374
0.2883760929107666
1.2208247184753418
0.28487396240234375
1.157322645187378
0.26278257369995117
1.2742435932159424
0.2841625213623047
0.22992420196533203
0.2743973731994629
1.1571228504180908
0.2745499610900879
1.3775303363800049
1.3881332874298096
0.26300883293151855
0.2981531620025635
0.24715924263000488
0.24147295951843262
0.23114657402038574
0.2366194725036621
0.2294168472290039
1.2487742900848389
0.24018120765686035
1.1916844844818115
0.268587589263916
0.22700214385986328
0.21803998947143555
0.23818659782409668
0.26958656311035156
0.23711204528808594
0.22988462448120117
0.21220827102661133
0.25671935081481934
0.288527250289917
0.24113845825195312
0.20284771919250488
0.23425650596618652
0.4964568614959717
829374341691346946 not found
0.2412097454071045
0.23919224739074707
0.27600741386413574
0.2667720317840576
0.2830052375793457
0.24464178085327148
0.23705148696899414
0.2429959774017334
0.2171165943145752
0.21361017227172852
0.23651862144470215
0.231370210647583
0.21500039100646973
0.2704918384552002
0.22446060180664062
0.21396350860595703
0.2341318130493164
0.22443199157714844
0.261824369430542
827228250799742977 not found
0.19907665252685547
0.25173473358154297
0.2868332862854004
1.168982982635498
1.4253215789794922
0.2461862564086914
1.3175628185272217
1.2717783451080322

0.23832297325134277
0.25354433059692383
1.2573096752166748
0.25187182426452637
0.2192397117614746
0.24236345291137695
0.2597072124481201
1.2890660762786865
0.23944425582885742
1.3042938709259033
0.2519395351409912
2.8053107261657715
0.2550795078277588
0.31601715087890625
0.2912619113922119
0.1980733871459961
0.27719950675964355
1.261850118637085
0.25916552543640137
0.25652480125427246
1.3853511810302734
0.26466870307922363
0.2531468868255615
0.24130535125732422
1.2777044773101807
0.24017691612243652
0.22581005096435547
0.2206122875213623
0.21148228645324707
0.23057985305786133
0.2398519515991211
0.2354888916015625
0.24860525131225586
0.2603754997253418
0.22454619407653809
0.22688794136047363
0.24483180046081543
0.23784923553466797
0.24425649642944336
0.23078536987304688
0.21853899955749512
0.225142240524292
0.2206861972808838
0.2390446662902832
0.22946739196777344
0.22533488273620605
0.20793843269348145
0.25952935218811035
0.2536759376525879
0.23700761795043945
0.22155284881591797
0.23268461227416992
0.2315971851348877
0.2118992805480957
0.24848103523254395
0.21442532539367676
0.23697519302368164
0.2749943733215332
0.23687458038330078
0.2337968349456787
0.22255206108093262
0.2332773208618164
3.8412179946899414
1.3714497089385986
0.26836585998535156
1.386136770248413
1.3831961154937744
0.23788976669311523
0.8454227447509766
0.5996770858764648
1.2908244132995605
0.22837185859680176
1.3025791645050049
0.24024677276611328
1.3909125328063965
0.8077981472015381
0.6755249500274658
0.24222874641418457
0.23184728622436523
0.24768733978271484
0.24364852905273438
0.2705104351043701
0.22177553176879883
0.23675870895385742
0.212982177734375
0.24649429321289062
0.2555370330810547
0.22201037406921387
0.22379803657531738
0.23160266876220703
0.26926612854003906
0.32146286964416504
0.2294445037841797
0.24038410186767578
0.22826886177062988
0.23265695571899414
0.22113275527954102
0.22610092163085938
0.23780536651611328
0.23159122467041016
0.2172253131866455
0.1957085132598877
0.23624134063720703
0.24818897247314453
0.1949319839477539
0.2348945140838623
0.2481095790863037
0.20212531089782715
0.23304200172424316
0.23758792877197266
0.22490167617797852
0.264066219329834
0.22035503387451172
1.3628029823303223
0.2462003231048584
1.405055284500122
812747805718642688 not found
0.21627211570739746
0.2541475296020508
1.248563528060913
0.2527592182159424
0.5005829334259033
0.2485806941986084
0.23236370086669922
0.22576546669006348
0.23720383644104004
0.2323899269104004
0.22576117515563965
0.20017170906066895
0.22016596794128418
0.22751355171203613
0.22484397888183594
0.23417973518371582
0.24157357215881348
0.22220897674560547
0.2360553741455078
0.22118616104125977
0.22347450256347656
0.2473616600036621
0.20089292526245117
0.20718789100646973
0.24649572372436523
0.24658656120300293
0.21005010604858398
0.22895288467407227
0.23056912422180176
0.2550935745239258
0.23443984985351562
0.4671900272369385
0.2381269931793213
0.23763608932495117
0.20072603225708008
0.2284388542175293
0.2533602714538574
0.2543158531188965
0.21628284454345703
0.7355170249938965
0.7659077644348145
1.3294270038604736
0.23682165145874023
0.8371191024780273
0.6594152450561523
0.8709506988525391
0.6036913394927979
1.4056909084320068
1.3678779602050781
1.3991062641143799
0.257190465927124
0.22647380828857422
0.255601167678833
0.23499107360839844
0.24470901489257812
0.26257824897766113
0.2489609718322754
0.23761868476867676
0.24600982666015625
0.22561955451965332
802247111496568832 not found
0.23193860054016113
0.2284562587738037
0.2613029479980469
0.215559720993042
0.36235928535461426
0.1942586898803711
0.2961697578430176
0.24824738502502441
0.29778194427490234
0.2337486743927002
0.22684431076049805
0.257871150970459
0.23071622848510742
0.24472379684448242
0.2421708106994629
0.24587368965148926
0.2353839874267578
0.2566251754760742
0.21894621849060059
0.274371862411499
0.24142050743103027
0.22891855239868164
0.2138538360595703
0.22254014015197754
0.20364809036254883
0.22288727760314941
0.7371692657470703
0.7594943046569824
3.783604621887207
0.2595677375793457
0.23537278175354004
0.24348902702331543
0.2529106140136719
0.24262714385986328
0.30950427055358887
0.2588496208190918
0.25865769386291504
0.23398375511169434
0.23441815376281738
0.2300879955291748
0.2469019889831543
0.23583269119262695
0.22111225128173828
0.22441339492797852
0.24704432487487793
0.20876121520996094
0.2491285800933838
0.22479581832885742
0.2220287322998047
0.2473752498626709
0.21140503883361816
0.2326490879058838
0.24115300178527832
0.21381449699401855
0.2449655532836914
1.3957242965698242
0.27881360054016113
1.3328542709350586
0.25029730796813965
0.20636630058288574
0.25415587425231934
0.24433255195617676
1.3094828128814697
0.23378539085388184
1.4048254489898682
0.8057446479797363
0.791100263595581
0.23878097534179688
0.2548098564147949
0.3389928340911865
0.2279069423675537
0.23870086669921875
0.2374734878540039
1.3770229816436768
1.3635973930358887
0.2387688159942627
1.3974683284759521
1.3426356315612793
0.25800132751464844
1.310338020324707
0.24434566497802734
0.27071380615234375
0.2669253349304199
0.23860621452331543
0.23102068901062012
0.23400187492370605
0.22838449478149414
0.26241016387939453
0.25038647651672363
0.24306368827819824
0.2596712112426758
0.4656941890716553
0.22658133506774902
0.22892475128173828
0.21040964126586914
0.8073761463165283
0.22733592987060547
0.23977398872375488
0.2504429817199707
0.26579737663269043
0.23230314254760742
0.23453593254089355
0.2605743408203125
0.20953965187072754
0.23931884765625
0.25333595275878906
0.23489069938659668
0.24068140983581543
0.23861408233642578
0.26196813583374023
0.24823784828186035
0.2261219024658203
0.2350318431854248
1.3580782413482666
1.2800755500793457
0.2583658695220947
0.8560378551483154
0.6288943290710449
1.4212474822998047
0.24376225471496582
1.3431260585784912
1.3971188068389893
0.8034636974334717
0.7842934131622314
0.23029136657714844
1.275805950164795
0.23249411582946777
0.23658061027526855
1.3272478580474854
0.2504913806915283
1.3511321544647217
0.24280667304992676
0.22601962089538574
0.2293853759765625
1.5353353023529053
0.2424631118774414
0.25928664207458496
0.23984789848327637
1.2720043659210205
0.2520740032196045
0.48265624046325684
0.23141813278198242
0.22817635536193848
0.2328166961669922
0.26029109954833984
0.24846291542053223
0.22202420234680176
0.23816275596618652
0.268035888671875
0.23081707954406738
0.25406694412231445
0.23545122146606445
0.234022855758667
0.29889488220214844
0.23039507865905762
0.26184535026550293
0.21503543853759766
0.231001615524292
0.2140638828277588
0.21113920211791992
0.2264268398284912
0.24156999588012695
0.23476839065551758
0.22150015830993652
0.22097349166870117
0.21975946426391602
0.1926872730255127
0.25363755226135254
0.21756958961486816
0.2231450080871582
0.23668313026428223
0.22388029098510742
0.20850062370300293
0.23173117637634277
0.19920873641967773
0.23492980003356934
1.3798370361328125
1.3734712600708008
0.254563570022583
0.25145792961120605
0.2337965965270996
0.27600646018981934
0.2457737922668457
0.28699469566345215
779123168116150273 not found
1.1944794654846191
0.23928260803222656
0.2531318664550781
0.8430829048156738
0.6191971302032471
0.28130459785461426
1.2798986434936523
1.357896089553833
0.2597503662109375
1.2891225814819336
0.24369478225708008
0.2417008876800537
0.23151755332946777
1.2605655193328857
0.2528219223022461
1.2443833351135254
0.24973583221435547
0.25040292739868164
0.24685001373291016
0.25069499015808105
0.2462928295135498
0.2288055419921875
0.23590493202209473
0.2189781665802002
0.25637292861938477
0.23934340476989746
0.22029733657836914
0.23157072067260742
0.2213134765625
0.21126604080200195
0.22189736366271973
0.4438643455505371
0.26360607147216797
0.21880531311035156
775096608509886464 not found
0.21324920654296875
0.24262690544128418
0.20724058151245117
0.20478510856628418
0.2646188735961914
0.22782516479492188
0.2359321117401123
0.22539663314819336
0.22002816200256348
0.21421265602111816
0.21687602996826172
0.23665761947631836
0.25826215744018555
0.2231125831604004
0.5531749725341797
0.24045848846435547
0.2281804084777832
1.3469018936157227
0.24606060981750488
0.2501542568206787
0.26847219467163086

1.3895659446716309
1.3917369842529297
0.2518503665924072
0.2663133144378662
1.2915244102478027
0.5245952606201172
0.2545592784881592
0.21722173690795898
0.24087977409362793
0.209442138671875
771004394259247104 not found
0.22526073455810547
0.22792458534240723
0.22592544555664062
770743923962707968 not found
0.22284340858459473
0.22495698928833008
0.22251200675964355
0.23380374908447266
0.24799513816833496
0.2303934097290039
0.24347376823425293
0.21107769012451172
0.238358736038208
0.24327516555786133
0.2767186164855957
0.23938894271850586
0.19472026824951172
0.2447507381439209
0.25929856300354004
0.2260279655456543
0.2500734329223633
0.19965624809265137
0.2283477783203125
0.22519707679748535
0.23170995712280273
0.2500326633453369
0.2372143268585205
766864461642756096 not found
0.17552542686462402
0.4764683246612549
0.27313661575317383
0.2159440517425537
0.2672903537750244
0.2526731491088867
0.35730624198913574
0.21929121017456055
0.20833992958068848
0.23573565483093262
1.287688970565796
0.25066614151000977
1.3876054286956787
0.3092954158782959
0.23714113235473633
1.299971342086792
0.23029136657714844
1.0577528476715088
0.47765493392944336
1.4118633270263672
0.23766851425170898
0.2523207664489746
1.3384504318237305
0.25502729415893555
0.5271437168121338
0.23488211631774902
0.2372913360595703
1.2723033428192139
0.26194000244140625
1.3898777961730957
0.281818151473999
0.2526419162750244
1.4009389877319336
0.42454957962036133
0.23829293251037598
3.1352779865264893
0.25268030166625977
0.24222469329833984
0.23261022567749023
0.22334027290344238
0.23620867729187012
0.23558926582336426
0.2534630298614502
0.22455501556396484
0.23959040641784668
0.22803950309753418
759923798737051648 not found
0.21361708641052246
0.2481245994567871
0.2315962314605713
759566828574212096 not found
0.19492030143737793
0.21142172813415527
0.2363128662109375
0.2568802833557129
0.23631000518798828
0.2595381736755371
0.36066174507141113
0.21757054328918457
0.22710299491882324

Rate limit reached. Sleeping for: 137

140.18998074531555
0.355496883392334
0.2675740718841553
0.2534174919128418
0.2546730041503906
0.24789881706237793
0.26247406005859375
0.23262643814086914
0.24254417419433594
1.2394561767578125
1.4297857284545898
0.25899839401245117
1.3073928356170654
1.3741004467010498
0.2589998245239258
0.27443408966064453
0.25756001472473145
4.459499835968018
0.2552511692047119
0.5668435096740723
0.23057126998901367
0.2251124382019043
0.22969388961791992
0.23592042922973633
0.23617839813232422
0.22045302391052246
0.22010135650634766
0.22728610038757324
0.2512626647949219
0.24400591850280762
0.27237534523010254
0.23648571968078613
0.2188429832458496
754011816964026368 not found
0.19222164154052734
0.2590785026550293
0.22717690467834473
0.2549891471862793
0.23777198791503906
0.2489311695098877
0.19819402694702148
0.21790027618408203
0.24340534210205078
0.23393774032592773
0.22968697547912598
0.23782038688659668
0.2107710838317871
0.2903733253479004
0.231217622756958
1.3937618732452393
1.369309902191162
0.24960803985595703
0.25524425506591797
0.2296125888824463
1.3951036930084229
0.79915452003479
0.7690515518188477
0.7314579486846924
0.7496364116668701
1.303771734237671
0.24531912803649902
1.4004640579223633
0.24472737312316895
1.3005962371826172
0.2470386028289795
1.3631160259246826
0.2604236602783203
0.25194692611694336
0.2823820114135742
0.265944242477417
0.24915480613708496
0.24034357070922852
0.25255322456359863
0.23762893676757812
0.2445213794708252
0.26972031593322754
0.23460102081298828
0.22496390342712402
0.2422046661376953
0.7906231880187988
0.2300858497619629
0.22688817977905273
0.22533416748046875
0.21097302436828613
0.23384356498718262
0.2556605339050293
0.23057913780212402
0.22656702995300293
0.28467345237731934
0.2549886703491211
0.2376868724822998
0.22859644889831543
0.21896648406982422
0.23387455940246582
0.19742488861083984
1.2547283172607422
0.23455262184143066
0.24889850616455078
1.282989740371704
0.23617124557495117
0.23044967651367188
0.22546029090881348
0.2244563102722168
0.4573540687561035
0.24652647972106934
0.23456907272338867
0.24645352363586426
0.2519385814666748
0.23184823989868164
0.2362995147705078
0.2633199691772461
0.23180532455444336
0.20722079277038574
0.22033143043518066
0.2645702362060547
0.20921754837036133
0.24527359008789062
0.24992012977600098
0.22514796257019043
0.22854399681091309
0.2613518238067627
0.22460579872131348
0.448314905166626
0.2129368782043457
0.22808051109313965
0.2688624858856201
0.2251567840576172
0.22313237190246582
0.25803494453430176
0.2319936752319336
0.23183655738830566
0.22889423370361328
0.21770691871643066
0.4709463119506836
0.23348236083984375
0.2239980697631836
0.22014808654785156
0.20348024368286133
0.21567130088806152
0.24286603927612305
0.27806687355041504
0.2267615795135498
0.4602782726287842
0.19907093048095703
0.2530026435852051
0.2977566719055176
0.45700860023498535
0.25051212310791016
0.46027088165283203
0.21053481101989746
0.22679901123046875
0.2629563808441162
0.23009967803955078
0.22534656524658203
0.2331557273864746
0.22720003128051758
0.2208271026611328
0.24834489822387695
0.20743274688720703
0.22513079643249512
0.23382210731506348
0.21935153007507324
0.28864574432373047
0.22368836402893066
0.2344503402709961
0.23542308807373047
0.20397067070007324
0.22595787048339844
0.22703075408935547
0.22803711891174316
0.2387254238128662
0.22562479972839355
0.19683098793029785
0.1985607147216797
0.23932647705078125
0.23093628883361816
0.1964716911315918
0.24844050407409668
0.24420475959777832
0.19292736053466797
0.2462596893310547
0.19588494300842285
0.2484891414642334
0.22844648361206055
0.22352385520935059
0.2058734893798828
0.2481081485748291
0.253248929977417
0.24674057960510254
0.22502994537353516
0.26169848442077637
0.22237038612365723
0.24271130561828613
0.8410701751708984
0.7572300434112549
1.3454277515411377
0.23153066635131836
1.3946857452392578
0.24756526947021484
0.813227653503418
0.7661468982696533
0.2325437068939209
0.25766611099243164
0.22352027893066406
0.21680331230163574
0.22027826309204102
0.25328660011291504
0.21567535400390625
0.23766136169433594
0.24181866645812988
0.20276308059692383
0.22473526000976562
0.21576523780822754
0.24098658561706543
0.22923874855041504
0.2529621124267578
0.27611780166625977
0.2351241111755371
0.21285653114318848
0.2885103225708008
0.19670510292053223
0.2119464874267578
0.24582266807556152
0.20411062240600586
0.2326822280883789
0.2268843650817871
0.221466064453125
0.20550084114074707
0.2349996566772461
0.2256758213043213
0.2450268268585205
0.22721433639526367
0.21271920204162598
0.24195337295532227
0.2094860076904297
0.2477424144744873
0.2327861785888672
0.22479987144470215
0.2626774311065674
0.23634672164916992
0.2680690288543701
0.21248197555541992
0.22098636627197266
0.22872018814086914
0.19515562057495117
0.23379778861999512
0.2326955795288086
0.22464752197265625
0.2311718463897705
0.2134721279144287
0.2428126335144043
0.24048089981079102
0.2147974967956543
0.2215564250946045
0.46598100662231445
0.23736095428466797
0.23596715927124023
0.20087218284606934
0.23282146453857422
0.22446465492248535
0.23569917678833008
0.21977663040161133
0.23733806610107422
0.21184277534484863
0.4492380619049072
0.22759723663330078
0.22405457496643066
0.22469258308410645
0.20292115211486816
0.22986173629760742
0.21853160858154297
0.22348737716674805
1.2537477016448975
0.24020600318908691
0.193129301071167
0.23210859298706055
0.2086338996887207
0.23617267608642578
0.21819567680358887
0.20273637771606445
0.24746131896972656
0.22243189811706543
0.19300174713134766
0.25420284271240234
0.2224745750427246
0.2158365249633789
0.23769426345825195
0.23308539390563965
0.22617220878601074
0.2250528335571289
0.26700615882873535
0.24704337120056152
0.21461248397827148
0.20180273056030273
0.2559630870819092
0.23218393325805664
0.20357918739318848
0.2067244052886963
0.23621654510498047
0.23975324630737305
0.21959829330444336
0.21779870986938477
0.24191808700561523
0.22632813453674316
0.24026060104370117
0.2355937957763672
0.20067191123962402
0.2106492519378662
0.23203182220458984
0.21621489524841309
0.21808767318725586
0.23185181617736816
0.20581817626953125
0.2681725025177002
0.23685789108276367
0.21310830116271973
0.21689677238464355
0.23676848411560059
0.2345132827758789
0.21873831748962402
0.20381808280944824
0.21875905990600586
0.24509072303771973
0.2091367244720459
0.24115943908691406
0.21056437492370605
0.21380066871643066
0.252638578414917
0.21575045585632324
0.2319180965423584
0.1973893642425537
0.22846508026123047
0.23505115509033203
0.23183822631835938
0.23459863662719727
0.23924589157104492
0.21035337448120117
0.20732712745666504
0.264798641204834
0.23981380462646484
0.2104635238647461
0.2899928092956543
0.2262260913848877
0.2209460735321045
0.25319600105285645
0.22254681587219238
0.2000713348388672
0.20886564254760742
0.21380090713500977
0.23150134086608887
0.24651527404785156
0.21169161796569824
0.19558954238891602
0.21727657318115234
0.2275562286376953
0.23209333419799805
0.23540353775024414
0.2106485366821289
0.2518892288208008
0.22986936569213867
0.2175757884979248
0.20031213760375977
0.21132540702819824
0.23357605934143066
0.22371864318847656
1.252457618713379
0.25090503692626953
1.253678798675537
0.24983930587768555
0.23234987258911133
0.2347700595855713
0.22357702255249023
0.24862027168273926
0.2280418872833252
0.19726276397705078
0.22054028511047363
0.23374295234680176
0.24024462699890137
0.2149500846862793
0.23253893852233887
0.24349761009216309
0.2659299373626709
0.21978402137756348
0.2260274887084961
0.24225783348083496
0.2318873405456543
0.22751975059509277
0.19416260719299316
0.4658081531524658
0.23471665382385254
0.24744820594787598
0.4433310031890869
0.246337890625
1.2716755867004395
0.2544252872467041
0.21291637420654297
0.23835325241088867
0.23953843116760254
0.22710204124450684
0.22224044799804688
0.20774388313293457
1.2360527515411377
0.23077964782714844
0.24051618576049805
0.20361590385437012
0.23122501373291016
0.2582714557647705
0.22821664810180664
0.21461892127990723
0.2646520137786865
0.19565248489379883
0.2556571960449219
0.20360970497131348
0.23624134063720703
0.22203969955444336
0.2297227382659912
0.22203588485717773
0.2777824401855469

0.24291229248046875
0.22777652740478516
0.2293863296508789
0.20047998428344727
0.24582982063293457
0.25327491760253906
0.23459315299987793
0.22439146041870117
0.22440314292907715
0.24365806579589844
0.2277979850769043
0.22965407371520996
1.325049877166748
0.23606038093566895
0.2243211269378662
0.260265588760376
0.2447643280029297
0.22862792015075684
0.25156712532043457
0.2251567840576172
0.26502418518066406
0.2363264560699463
0.23085665702819824
0.22413134574890137
0.21303558349609375
0.21921658515930176
1.437765121459961
0.22698163986206055
0.22763824462890625
0.4869203567504883
2.4791669845581055
0.8298943042755127
0.7730004787445068
0.22706842422485352
0.301328182220459
0.2310316562652588
0.22769737243652344
0.24423456192016602
0.21986675262451172
0.19601011276245117
3.7949392795562744
0.24883770942687988
0.25127363204956055
0.23818373680114746
1.3091466426849365
0.24453234672546387
0.2258739471435547
0.3032364845275879
0.23233461380004883
1.3990108966827393
0.8251304626464844
0.757077693939209
0.2698800563812256
0.2467327117919922
0.24828171730041504
0.2468411922454834
1.295300006866455
1.5327014923095703
0.2403421401977539
1.3535127639770508
0.5086262226104736
1.0884552001953125
1.3977959156036377
1.3528852462768555
0.2591989040374756
1.3988540172576904
0.25293922424316406
1.2697410583496094
0.24652552604675293
1.3032431602478027
1.3511378765106201
0.23964238166809082
0.24434280395507812
0.24733304977416992
0.2263646125793457
0.23427104949951172
0.2215433120727539
0.2283470630645752
0.2116703987121582
0.2510807514190674
0.24193096160888672
0.2245025634765625
0.23199701309204102
0.23818564414978027
0.40604615211486816
0.23135662078857422
0.2070460319519043
0.20917630195617676
0.3110659122467041
0.2298450469970703
0.2532641887664795
0.24633288383483887
0.2366316318511963
0.2124776840209961
0.22936129570007324
0.1991128921508789
0.22100567817687988
0.2636682987213135
0.22099876403808594
0.2108597755432129
0.22775983810424805
0.24788880348205566
0.21603083610534668
0.251922607421875
0.18761873245239258
4.611194133758545
0.2396535873413086
0.240509033203125
0.47531747817993164
0.26694297790527344
0.22931838035583496
0.2415323257446289
0.23916029930114746
0.25519299507141113
0.24918031692504883
0.23289966583251953
0.20509886741638184
0.21802902221679688
0.22742438316345215
0.21257400512695312
0.24265050888061523
0.2128739356994629
0.2503345012664795
0.2424468994140625
0.22560954093933105
0.2141709327697754
0.26736021041870117
0.2434689998626709
0.2082841396331787
0.20460224151611328
0.2344498634338379
0.224839448928833
0.24513792991638184
0.22576546669006348
1.243196964263916
0.24263238906860352
0.20183968544006348
0.23787474632263184
0.22305679321289062
0.20966291427612305
0.19983386993408203
0.23460054397583008
0.20533204078674316
0.22835445404052734
0.2181541919708252
0.19506192207336426
1.372070074081421
0.23388934135437012
1.3751025199890137
0.26512718200683594
1.3023583889007568
1.3081209659576416
0.2476792335510254
0.23854756355285645
0.22049260139465332
0.49010634422302246
1.016733169555664
0.39380478858947754
0.24077749252319336
0.22834348678588867
0.2467348575592041
0.20293164253234863
0.24358797073364258
0.21019434928894043
0.30153512954711914
0.2354140281677246
0.22084903717041016
0.19889616966247559
0.24851155281066895
0.2897148132324219
0.22540593147277832
0.22405123710632324
0.2595047950744629
0.23541927337646484
0.2333064079284668
0.22281122207641602
0.20807552337646484
0.2318887710571289
0.23414325714111328
0.23061084747314453
0.2326667308807373
0.22032856941223145
0.2297506332397461
0.23687481880187988
0.19166350364685059
0.2356576919555664
0.2434711456298828
0.22376298904418945
0.21645450592041016
0.24059009552001953
0.24004101753234863
0.2302849292755127
0.23798060417175293
0.23015785217285156
0.22230052947998047
0.24123883247375488
0.24529457092285156
0.23122286796569824
0.21550202369689941
0.4900932312011719
1.0478641986846924
0.31080007553100586
0.22153830528259277
0.2647116184234619
0.4785909652709961
0.24267148971557617
1.317317008972168
0.2538416385650635
1.385801076889038
1.4820127487182617
0.23174762725830078
0.2278130054473877
0.19674968719482422
0.23911690711975098
0.24812674522399902
1.3770606517791748
0.5527162551879883
1.2816667556762695
0.24216651916503906
0.8366608619689941
1.488577127456665
0.6382684707641602
0.25240540504455566
0.19407415390014648
1.3279995918273926
0.22032451629638672
1.2971112728118896
0.2495574951171875
0.23897242546081543
1.2387356758117676
1.1638751029968262
0.32178330421447754
1.3647222518920898
0.23208999633789062
0.24433064460754395
0.21921467781066895
0.2364799976348877
0.23320436477661133
0.23189377784729004
0.22198152542114258
0.23752713203430176
0.2184593677520752
0.23517870903015137
0.22373175621032715
0.24461698532104492
0.24660634994506836
0.24887752532958984
0.5346360206604004
0.22611236572265625
0.21600580215454102
0.23403406143188477
0.21633458137512207
0.22143864631652832
0.19355320930480957
0.25371670722961426
0.22427129745483398
0.22267985343933105
0.23108458518981934
0.2410430908203125
0.2697324752807617
0.24585485458374023
0.22481155395507812
0.21662402153015137
0.2359933853149414
0.22920823097229004
0.22815608978271484
0.23820829391479492
0.23633408546447754
0.23570752143859863
1.3931231498718262
0.24344587326049805
1.2873308658599854
0.5174415111541748
1.0484278202056885
0.2237381935119629
0.23054242134094238
0.23339319229125977
0.23452162742614746
0.22688579559326172
1.3725061416625977
0.24841666221618652
0.2254931926727295
0.25588393211364746
3.8105320930480957
0.23558425903320312
0.21307802200317383
0.23949956893920898
0.2566690444946289
0.23833107948303223
0.44893813133239746
0.2547018527984619
0.25534582138061523
0.21863913536071777
0.23084378242492676
0.22084856033325195
0.2325901985168457
0.2111341953277588
0.240004301071167
0.22928929328918457
0.20318317413330078
0.22600173950195312
0.21955108642578125
0.21212220191955566
0.22072386741638184
0.24227094650268555
0.22295236587524414
0.21349120140075684
0.2145373821258545
0.21851682662963867
0.21853923797607422
0.2374715805053711
0.20799732208251953
0.22096824645996094
0.23666167259216309
0.23667645454406738
0.23645448684692383
0.21656560897827148
0.46576929092407227
0.25351858139038086
0.21422815322875977
0.22542548179626465
0.22867751121520996
1.3075392246246338
1.294064998626709
0.2258284091949463
0.24660730361938477
1.2159175872802734
0.22464799880981445
0.29660463333129883
0.24265432357788086
1.3523235321044922
1.4349238872528076
0.2553274631500244
0.4550759792327881
0.2264103889465332
0.25743627548217773
1.3839037418365479
1.2590994834899902
0.2165367603302002
1.369232416152954
1.5234081745147705
0.2241044044494629
0.28399038314819336
0.23160862922668457
1.2855339050292969
1.3367493152618408
0.21210360527038574
1.3460354804992676
0.2408125400543213
1.3400847911834717
0.42972683906555176
0.24667716026306152
1.3287947177886963
0.22117328643798828
1.2916498184204102
1.285759687423706
0.2106931209564209
0.22373008728027344
0.22179174423217773
0.21573901176452637
0.21483278274536133
0.21700716018676758
1.2667694091796875
0.20694875717163086
1.3439254760742188
0.22358083724975586
0.22187447547912598
0.2170884609222412
0.21175217628479004
0.22479510307312012
0.4687073230743408
1.0012195110321045
0.7582993507385254
0.7510535717010498
0.22184205055236816
0.44503045082092285
0.22509074211120605
0.22908806800842285
3.4097118377685547
4.958542108535767
0.23321080207824707
0.2033524513244629
0.22360467910766602
0.20981431007385254
0.2029285430908203
0.2127368450164795
0.2010810375213623
0.22835206985473633
0.21611547470092773
4.503377914428711
0.2144758701324463
3.339362382888794
0.23300909996032715
0.22658085823059082
0.2556588649749756
1.3352372646331787
1.365893840789795
0.22591567039489746
1.3736441135406494
0.275317907333374
0.21841764450073242
0.22234511375427246
0.22869563102722168
0.22222471237182617
1.319622278213501
1.3312783241271973
0.22794532775878906
1.3942925930023193
0.2457408905029297
1.3295927047729492
680055455951884288 not found
0.19505858421325684
0.23486542701721191
0.294064998626709
1.3176686763763428
0.24442291259765625
0.22490262985229492
0.3030061721801758
0.22127604484558105
1.2165744304656982

0.21578049659729004
0.22441935539245605
0.19812774658203125
0.2151188850402832
0.4377286434173584
0.2111363410949707
0.2223961353302002
0.22011303901672363
0.23076891899108887
0.2021803855895996
0.2155287265777588
0.1959078311920166
0.21720290184020996
0.22335004806518555
0.2202749252319336
0.1994791030883789
0.22292113304138184
0.21631860733032227
0.22134160995483398
0.22327017784118652
0.21991443634033203
0.20499396324157715
0.21566104888916016
0.21662545204162598
0.21321582794189453
0.21393179893493652
0.20653009414672852
0.2143568992614746
0.24307632446289062
0.24120664596557617
0.23612213134765625
0.2533552646636963
0.19483494758605957
0.21130633354187012
0.21718311309814453
0.2094430923461914
0.22684693336486816
0.20830941200256348
0.2288835048675537
0.2127702236175537
0.21131062507629395
0.22554898262023926
0.2280101776123047
0.218428373336792
0.2354745864868164
0.22786283493041992
0.219773530960083
0.20525836944580078
0.2643568515777588
0.21847224235534668
0.22929859161376953
0.22552752494812012
0.23018884658813477
0.2364788055419922
0.21380305290222168
0.23129510879516602
0.21282529830932617
3.62266206741333
0.2538723945617676
0.4764211177825928
0.33455967903137207
0.5280935764312744
0.2028357982635498

Rate limit reached. Sleeping for: 544

0.2669548988342285
546.6347184181213
0.24726653099060059
0.2501990795135498
0.2489933967590332
0.2517533302307129
0.22674226760864258
0.23390769958496094
0.2266995906829834
0.2763998508453369
0.23515081405639648
0.30548906326293945
0.23512649536132812
0.21346426010131836
0.2182929515838623
0.22669053077697754
0.26489782333374023
0.22392702102661133
0.21087265014648438
0.24573659896850586
0.22788739204406738
0.21704936027526855
0.20082926750183105
0.23878693580627441
0.24144768714904785
0.22299408912658691
0.23769164085388184
0.2018299102783203
0.21990728378295898
0.2412097454071045
0.2213430404663086
0.244828462600708
0.22344326972961426
0.22827458381652832
0.21826624870300293
0.22866392135620117
0.22458124160766602
0.2022712230682373
0.21278929710388184
0.23600053787231445
0.2722208499908447
0.2452242374420166
0.22387933731079102
0.22388601303100586
0.2198026180267334
0.21830105781555176
0.22649288177490234
0.22098731994628906
0.23571038246154785
0.19994497299194336
0.23081254959106445
0.2530057430267334
0.22380995750427246
0.21342754364013672
0.2190086841583252
0.23445940017700195
0.23472809791564941
0.2219233512878418
0.28193187713623047
0.2329263687133789
0.2267451286315918
0.26810598373413086
0.21793437004089355
0.2617793083190918
0.23636579513549805
0.21422672271728516
0.1997241973876953
0.2463672161102295
0.23387622833251953
0.22989535331726074
0.21750593185424805
0.23536467552185059
0.2266864776611328
0.22759532928466797
0.18365883827209473
0.24097323417663574
0.19820666313171387
0.23458123207092285
0.2179567813873291
0.22757482528686523
0.22703218460083008
0.197462797164917
0.2348475456237793
0.2153184413909912
0.21738171577453613
0.22303533554077148
0.20746493339538574
0.2180469036102295
0.22539830207824707
0.21215176582336426
0.31760668754577637
0.20996785163879395
0.21404385566711426
0.23284554481506348
0.19186067581176758
0.21301770210266113
0.23595142364501953
0.2285919189453125
0.21823525428771973
0.21202969551086426
0.25630760192871094
0.20908045768737793
0.2321009635925293
0.21990132331848145
0.2421870231628418
0.24141335487365723
0.25829267501831055
0.21851229667663574
0.21588921546936035
0.24508285522460938
0.21711063385009766
0.2099759578704834
0.22892069816589355
0.22217798233032227
0.23292970657348633
0.22112059593200684
0.2119758129119873
0.251326322555542
0.22031188011169434
0.24489641189575195
0.23425912857055664
0.19672679901123047
0.2242751121520996
0.2317345142364502
0.23192882537841797
0.21765518188476562
0.23227858543395996
0.20819330215454102
0.21229124069213867
0.2238149642944336
0.22633910179138184
0.20690345764160156
0.22727441787719727
0.22986650466918945
0.21942353248596191
0.22535920143127441
0.2053525447845459
0.22787880897521973
0.21288061141967773
0.2221999168395996
0.2458789348602295
0.21058440208435059
0.21904754638671875
0.22356605529785156
0.22452807426452637
0.2445838451385498
0.23840785026550293
0.20949029922485352
0.19399499893188477
0.17726540565490723
0.23691678047180176
0.23145318031311035
0.22451162338256836
0.19424009323120117
0.23125886917114258
0.2411363124847412
0.1999342441558838
0.22809410095214844
0.24598956108093262
0.22496891021728516
0.2286832332611084
0.22271442413330078
0.22505450248718262
0.22684741020202637
0.23020291328430176
0.2368161678314209
0.20008015632629395
0.23718929290771484
0.20074844360351562
0.24673795700073242
0.29355335235595703
0.21684670448303223
0.1907939910888672
0.2800612449645996
0.2203066349029541
0.2210850715637207
0.2222423553466797
0.22426748275756836
0.22906208038330078
0.20957183837890625
0.24392008781433105
0.18915009498596191
0.22429561614990234
0.2362990379333496
0.22618699073791504
0.2564120292663574
0.24471688270568848
0.30712890625
0.24480795860290527
0.24119901657104492
0.21932172775268555
0.21472430229187012
0.20402121543884277
0.2448408603668213
0.2620067596435547
0.2083888053894043
0.21728110313415527
0.203416109085083
0.21503949165344238
0.2320864200592041
0.21218419075012207
0.24781274795532227
0.22092127799987793
0.2069709300994873
0.19428539276123047
0.23261260986328125
0.2255392074584961
0.26732945442199707
0.21643519401550293
0.2147047519683838
0.22829985618591309
0.22783327102661133
0.19534039497375488
0.23769783973693848
0.2129361629486084
0.26871347427368164
0.2156507968902588
0.22138428688049316
0.19956421852111816
0.2831540107727051
0.24021077156066895
0.22846007347106934
0.19090652465820312
0.2296133041381836
0.20323586463928223
0.22185683250427246
0.23222112655639648
0.23018670082092285
0.2221231460571289
0.19133448600769043
0.20682406425476074
0.2145543098449707
0.21576428413391113
0.2383115291595459
0.201568603515625
0.22377514839172363
0.2278280258178711
0.21739768981933594
0.21715998649597168
0.26561498641967773
0.23624372482299805
0.190718412399292
0.23504352569580078
0.22391080856323242
0.2614903450012207
0.21082711219787598
0.21487021446228027
0.2286360263824463
0.2251288890838623
0.21034646034240723
0.2559027671813965
0.2574937343597412
0.22777843475341797
0.2438650131225586
0.22253060340881348
0.24730181694030762
0.2865731716156006
0.23580360412597656
0.22599005699157715
0.2105576992034912
0.22284913063049316
0.2705810070037842
0.19480228424072266
0.22232532501220703
0.23528790473937988
0.21920275688171387
0.22892379760742188
0.2177114486694336
0.21608662605285645
0.26346921920776367
0.22991275787353516
0.22651457786560059
0.2646667957305908
0.21043753623962402
0.22566938400268555
0.21144628524780273
0.2393639087677002
0.22703123092651367
0.2158679962158203
0.1900324821472168
0.2552814483642578
0.2272350788116455
0.19524741172790527
0.22401785850524902
0.23760008811950684
0.22657394409179688
0.21960949897766113
0.19630980491638184
0.19914579391479492
0.21943235397338867
0.22902369499206543
0.20106220245361328
0.21273016929626465
0.19556879997253418
0.2507612705230713
0.23594045639038086
0.22333216667175293
0.21073460578918457
0.2200157642364502
0.24151372909545898
0.2371997833251953
0.22969388961791992
0.2057178020477295
0.2678389549255371
0.25035881996154785
0.23031210899353027
0.20553135871887207
0.21016478538513184
0.23609280586242676
0.20366883277893066
0.22606301307678223
0.23533892631530762
0.1904900074005127
0.22959613800048828
0.2282881736755371
0.21598553657531738
0.21598267555236816
0.2194836139678955
0.2111680507659912
0.2032787799835205
0.22991704940795898
0.2467641830444336
0.2335505485534668
0.1879417896270752
0.2225031852722168
0.22853755950927734
0.2489168643951416
0.21125268936157227
0.2420973777770996
0.2202610969543457
0.2563619613647461
0.22411227226257324
0.2261209487915039
0.23412299156188965
0.2101283073425293
0.22077584266662598
0.23555541038513184
0.21518707275390625
0.25615835189819336
0.2511730194091797
0.22891879081726074
0.22933053970336914
0.19743847846984863
0.23686671257019043
0.21466779708862305
0.242509126663208
0.21156764030456543
0.23342037200927734
0.1893301010131836
0.2284090518951416
0.2239668369293213
0.26220107078552246
0.18866729736328125
0.2083747386932373
0.2349705696105957
0.21469330787658691
0.21385478973388672
0.22896623611450195
0.2129523754119873
0.19165396690368652
0.22687149047851562
0.1987767219543457
0.19828033447265625
0.23120570182800293
0.2175910472869873
0.2512342929840088
0.21755075454711914
0.21832036972045898
0.21786785125732422
0.2127397060394287
0.1878528594970703
0.21132469177246094
0.23624920845031738
0.21785306930541992
0.20281505584716797
0.19098305702209473
0.24305415153503418
0.21123886108398438
0.20830106735229492
0.20618629455566406
0.20587587356567383
0.22585368156433105
0.22043919563293457
0.20926380157470703
0.2184138298034668
0.24608063697814941
0.20297718048095703
0.21664214134216309
0.20841193199157715
0.24971723556518555
0.21631360054016113
0.22159218788146973
0.2088150978088379
0.2160346508026123
0.21752548217773438
0.2184429168701172
0.2518024444580078
0.23077082633972168
0.20665335655212402
0.20801281929016113
0.2493300437927246
0.22492122650146484
0.22734808921813965
0.2321333885192871
0.20104026794433594
0.22353434562683105
0.23808956146240234
0.19794893264770508
0.2516040802001953
0.22593307495117188
0.21832776069641113
0.23342251777648926
0.20641303062438965
0.23825979232788086
0.23054194450378418
0.22106361389160156
0.19358420372009277

0.23012304306030273
0.23892545700073242
0.2205181121826172
0.21590733528137207
0.2280588150024414
0.25614404678344727
0.24828624725341797
0.2328629493713379
0.234175443649292
0.23793506622314453
0.23022937774658203
0.21640682220458984
0.22371363639831543
0.22788786888122559
0.21809625625610352
0.2081599235534668
0.2451181411743164
0.19838213920593262
0.2226696014404297
0.22081613540649414
0.2388916015625
0.22721624374389648
0.20105862617492676
0.2028360366821289
0.22164344787597656
0.2187788486480713
0.22309350967407227
0.21454548835754395
0.18937087059020996
0.1985321044921875
0.2230517864227295
0.22130227088928223
0.21378564834594727
0.217482328414917
0.23570466041564941
0.20077943801879883
0.22718524932861328
0.20514369010925293
0.22154712677001953
0.25380516052246094
0.21794390678405762
0.20792579650878906
0.21893024444580078
0.23037958145141602
0.2100374698638916
0.24060940742492676
0.21659111976623535
0.20149493217468262
0.19947433471679688
0.23663878440856934
0.23557662963867188
0.2071688175201416
0.19659948348999023
0.22643733024597168
0.2606346607208252
0.19087767601013184
0.21196293830871582
0.2454841136932373
0.20506000518798828
0.21344351768493652
0.23995375633239746
0.19244766235351562
0.2310624122619629
0.2532041072845459
0.2014477252960205
0.22966909408569336
0.26172542572021484
0.23603105545043945
0.21006488800048828
0.24024081230163574
0.22447896003723145
0.2385110855102539
0.22927522659301758
0.22898292541503906
0.21742987632751465
0.22992563247680664
0.2375023365020752
0.2015526294708252
0.23042559623718262
0.24331235885620117
0.20912909507751465
0.23327922821044922
0.23088788986206055
0.2069087028503418
0.207749605178833
0.21372604370117188
0.22710752487182617
0.2413187026977539
0.2231752872467041
0.2149662971496582
0.22658944129943848
0.20773553848266602
0.21928691864013672
0.22949433326721191
0.2200913429260254
0.23411774635314941
0.21072053909301758
0.22742033004760742
0.22376775741577148
0.21279668807983398
0.20750713348388672
0.19453883171081543
0.23640823364257812
0.22454190254211426
0.19147777557373047
0.24857401847839355
0.28092360496520996
0.22534966468811035
0.211151123046875
0.18601512908935547
0.2417316436767578
0.2274610996246338
0.2274937629699707
0.22564387321472168
0.19950509071350098
0.20308136940002441
0.22906875610351562
0.23441767692565918
0.18764090538024902
0.23436808586120605
0.23867058753967285
0.2342362403869629
0.20955657958984375
0.24715471267700195
0.21983122825622559
0.22672319412231445
0.24512004852294922
0.22417616844177246
0.23563432693481445
0.19153141975402832
0.2442014217376709
0.23278331756591797
0.21653270721435547
0.2254631519317627
0.2660071849822998
0.22085833549499512
0.226792573928833
0.2227792739868164
0.23109817504882812
0.21638894081115723
0.19457626342773438

In [58]:
# create empty list
json_data = []

# read file
with open("tweet_json.txt","r") as file:
    
    # iterate through each line
    for line in file:
        
        # convert line to dictionary and add to list
        json_data.append(json.loads(line))

In [60]:
# identify data to retrieve from first item in list
print(json_data[0]["id"])
print(json_data[0]["retweet_count"])
print(json_data[0]["favorite_count"])

892420643555336193
6879
32919

In [63]:
# create empty list to store data
json_data_retweets_favorites = []

# iterate through each item in list
for item in json_data:
    
    # add to list specific data, as dictionary
    json_data_retweets_favorites.append({
        "tweet_id": item["id"],
        "retweet_count": item["retweet_count"],
        "favorite_count": item["favorite_count"]
    })

In [65]:
# convert list of dicts to dataframe
df_retweets_favorites = pd.DataFrame(json_data_retweets_favorites)

In [66]:
# check data stored correctly
df_retweets_favorites

                tweet_id  retweet_count  favorite_count
0     892420643555336193           6879           32919
1     892177421306343426           5180           28450
2     891815181378084864           3423           21375
3     891689557279858688           7087           35886
4     891327558926688256           7600           34323
...                  ...            ...             ...
2320  666049248165822465             35              85
2321  666044226329800704            113             243
2322  666033412701032449             35              98
2323  666029285002620928             39             111
2324  666020888022790149            416            2232

[2325 rows x 3 columns]

# Assessing the data
We now have 3 dataframes to assess:
- df_twitter_archive - the dataFrame with the Twitter Archive data
- df_image_predictions - the dataframe with the image predictions data
- df_retweets_favorites - the dataframe witht the retweets and favorites data

### Assessing df_twitter_archive
I first used the sample method to returm a random sample of 10 rows to visually assess the data:

In [70]:
df_twitter_archive.sample(10)

,tweet_id,in_reply_to_status_id,in_reply_to_user_id,timestamp,source,text,retweeted_status_id,retweeted_status_user_id,retweeted_status_timestamp,expanded_urls,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo
230,847978865427394560,NaN,NaN,2017-04-01 01:08:10 +0000,"<a href=""http://twitter.com/download/iphone"" r...",RT @dog_rates: This is Charlie. He fell asleep...,8.323699e+17,4.196984e+09,2017-02-16 23:23:38 +0000,https://twitter.com/dog_rates/status/832369877...,11,10,Charlie,None,None,None,None
760,778383385161035776,NaN,NaN,2016-09-21 00:00:35 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Nala. She's a future Dogue model. Won'...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/778383385...,13,10,Nala,None,None,None,None
1918,674271431610523648,NaN,NaN,2015-12-08 16:56:51 +0000,"<a href=""http://twitter.com/download/iphone"" r...","""AT DAWN, WE RIDE""\n10/10 for both dogs https:...",NaN,NaN,NaN,https://twitter.com/dog_rates/status/674271431...,10,10,None,None,None,None,None
1165,722974582966214656,NaN,NaN,2016-04-21 02:25:47 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Happy 4/20 from the squad! 13/10 for all https...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/722974582...,4,20,None,None,None,None,None
1427,697630435728322560,NaN,NaN,2016-02-11 03:57:11 +0000,"<a href=""http://vine.co"" rel=""nofollow"">Vine -...",Pls make sure ur dogs have gone through some b...,NaN,NaN,NaN,https://vine.co/v/in7ZzHPKzWz,8,10,None,None,None,None,None
124,868639477480148993,NaN,NaN,2017-05-28 01:26:04 +0000,"<a href=""http://twitter.com/download/iphone"" r...",RT @dog_rates: Say hello to Cooper. His expres...,8.685523e+17,4.196984e+09,2017-05-27 19:39:34 +0000,"https://www.gofundme.com/3ti3nps,https://twitt...",12,10,Cooper,None,None,None,None
549,805207613751304193,NaN,NaN,2016-12-04 00:30:29 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Shooter. He's doing quite the snowy zo...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/805207613...,12,10,Shooter,None,None,None,None
1058,741793263812808706,NaN,NaN,2016-06-12 00:44:30 +0000,"<a href=""http://twitter.com/download/iphone"" r...",When your crush won't pay attention to you. Bo...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/741793263...,10,10,None,None,None,None,None
623,796031486298386433,NaN,NaN,2016-11-08 16:47:50 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Daisy. She's here to make your day bet...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/796031486...,13,10,Daisy,None,None,None,None
279,839990271299457024,NaN,NaN,2017-03-10 00:04:21 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Meet Sojourner. His nose is a Fibonacci Spiral...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/839990271...,13,10,Sojourner,None,None,None,None

#### From visual assessment:

##### Tidiness issues:
- Only 1 column needed for dog stage (i.e. doggo, floofer, pupper, puppo)

##### Quality issues:
- `rating_denominator` is 20 in 1 row. Expected vbalue is 10
- `Dog stage` values of "None" string should be replaced with Null
- Only want original tweets. Dataset includes data where `retweeted_status_id` is not null

After completing my visual assessment I continued my assessment of the data using programatic assessment:

In [71]:
df_twitter_archive.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2356 entries, 0 to 2355
Data columns (total 17 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   tweet_id                    2356 non-null   int64
 1   in_reply_to_status_id       78 non-null     float64
 2   in_reply_to_user_id         78 non-null     float64
 3   timestamp                   2356 non-null   object
 4   source                      2356 non-null   object
 5   text                        2356 non-null   object
 6   retweeted_status_id         181 non-null    float64
 7   retweeted_status_user_id    181 non-null    float64
 8   retweeted_status_timestamp  181 non-null    object
 9   expanded_urls               2297 non-null   object
 10  rating_numerator            2356 non-null   int64
 11  rating_denominator          2356 non-null   int64
 12  name                        2356 non-null   object
 13  doggo                       2356 non-null   object
 14  floofer                     2356 non-null   object
 15  pupper                      2356 non-null   object
 16  puppo                       2356 non-null   object
dtypes: float64(4), int64(3), object(10)
memory usage: 313.0+ KB

##### Quality issues:
- `tweet_id` is stored as integer type, but won't be used for calcs, should change to object type.
- `timestamp` is stored as object. Perhaps this should be stored as a more appropriate data type?
- `retweeted_status_id` has 181 non null values. Indicates 181 retweets to be removed
- `expanded_urls` has 2297 non nulls out of 2356 records. Therefore 59 records have no attached picture and will need to be removed.
- `retweeted_status_id` stored as float, but will not be used for calculations. Perhaps should be converted to object?
- `in_reply_to_status_id` stored as float, but will not be used for calculations. Perhaps should be converted to object?

In [72]:
df_twitter_archive["rating_numerator"].value_counts()

12      558
11      464
10      461
13      351
9       158
8       102
7        55
14       54
5        37
6        32
3        19
4        17
2         9
1         9
75        2
15        2
420       2
0         2
80        1
144       1
17        1
26        1
20        1
121       1
143       1
44        1
60        1
45        1
50        1
99        1
204       1
1776      1
165       1
666       1
27        1
182       1
24        1
960       1
84        1
88        1
Name: rating_numerator, dtype: int64

##### Quality issues:
- Looking at value counts, it appears some numerator values are incorrect. Perhaps values from 0-20 are correct?
- Excluding values above 20 will not signifcantly affect data size due to low volumes.

In [73]:
df_twitter_archive["rating_denominator"].value_counts()

10     2333
11        3
50        3
20        2
80        2
70        1
7         1
15        1
150       1
170       1
0         1
90        1
40        1
130       1
110       1
16        1
120       1
2         1
Name: rating_denominator, dtype: int64

##### Quality issues:
- small number of rows (23 rows) where denominator is not equal to 10
- Perhaps these values can be excluded as this will not signifcantly affect data size due to low volumes

In [74]:
df_twitter_archive["name"].value_counts()

None          745
a              55
Charlie        12
Cooper         11
Lucy           11
             ...
Dex             1
Ace             1
Tayzie          1
Grizzie         1
Christoper      1
Name: name, Length: 957, dtype: int64

##### Quality issues:
- name value of "a" appears to be incorrect
- large number of cases where name is None. Perhaps name can be identified from text?

In [83]:
df_twitter_archive.groupby(["doggo","floofer","pupper","puppo"])["tweet_id"].count().reset_index()

   doggo  floofer  pupper  puppo  tweet_id
0   None     None    None   None      1976
1   None     None    None  puppo        29
2   None     None  pupper   None       245
3   None  floofer    None   None         9
4  doggo     None    None   None        83
5  doggo     None    None  puppo         1
6  doggo     None  pupper   None        12
7  doggo  floofer    None   None         1

- Large number of cases where dog stage is not identified, perhaps this can be identified by text or some other means?
- 14 cases where 2 dog stages are present. Perhaps this can be concatinated?

### Assessing df_image_predictions

In [69]:
df_image_predictions.sample(10)

,tweet_id,jpg_url,img_num,p1,p1_conf,p1_dog,p2,p2_conf,p2_dog,p3,p3_conf,p3_dog
1584,797236660651966464,https://pbs.twimg.com/media/CxBafisWQAAtJ1X.jpg,2,collie,0.767005,True,Border_collie,0.100844,True,kelpie,0.048368,True
76,667435689202614272,https://pbs.twimg.com/media/CUM1OHCW4AEgGSi.jpg,1,Rottweiler,0.999091,True,miniature_pinscher,0.000450,True,black-and-tan_coonhound,0.000157,True
943,704347321748819968,https://pbs.twimg.com/media/CcZYJniXEAAEJRF.jpg,1,teddy,0.233378,False,feather_boa,0.088474,False,Brittany_spaniel,0.082917,True
1503,784826020293709826,https://pbs.twimg.com/media/CuRDF-XWcAIZSer.jpg,1,chow,0.090341,True,binoculars,0.083499,False,Irish_setter,0.077456,True
1682,813910438903693312,https://pbs.twimg.com/media/C0uXObSXUAAIzmV.jpg,1,Siberian_husky,0.699355,True,Eskimo_dog,0.256433,True,Norwegian_elkhound,0.013189,True
619,680440374763077632,https://pbs.twimg.com/ext_tw_video_thumb/68044...,1,space_heater,0.920367,False,radiator,0.049933,False,electric_fan,0.006719,False
3,666044226329800704,https://pbs.twimg.com/media/CT5Dr8HUEAA-lEu.jpg,1,Rhodesian_ridgeback,0.408143,True,redbone,0.360687,True,miniature_pinscher,0.222752,True
1481,780931614150983680,https://pbs.twimg.com/media/CtZtJxAXEAAyPGd.jpg,1,padlock,0.731564,False,necklace,0.065462,False,chain,0.036469,False
385,673345638550134785,https://pbs.twimg.com/media/CVg0SVRWEAAsBrS.jpg,1,hamster,0.761025,False,weasel,0.069362,False,Pomeranian,0.064627,True
1565,793845145112371200,https://pbs.twimg.com/media/CwRN8H6WgAASe4X.jpg,1,Old_English_sheepdog,0.765277,True,Bedlington_terrier,0.112753,True,Kerry_blue_terrier,0.047662,True

In [85]:
df_image_predictions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2075 entries, 0 to 2074
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   tweet_id  2075 non-null   int64
 1   jpg_url   2075 non-null   object
 2   img_num   2075 non-null   int64
 3   p1        2075 non-null   object
 4   p1_conf   2075 non-null   float64
 5   p1_dog    2075 non-null   bool
 6   p2        2075 non-null   object
 7   p2_conf   2075 non-null   float64
 8   p2_dog    2075 non-null   bool
 9   p3        2075 non-null   object
 10  p3_conf   2075 non-null   float64
 11  p3_dog    2075 non-null   bool
dtypes: bool(3), float64(3), int64(2), object(4)
memory usage: 152.1+ KB

In [86]:
df_image_predictions["img_num"].value_counts()

1    1780
2     198
3      66
4      31
Name: img_num, dtype: int64

Comments:
- Each entry has an image as expected
- Image number appears to be correct

##### Quality Issues:
- `tweet_id` is stored as integer type, but won't be used for calcs, should change to object type.

##### Tidiness issue:
- No need for this data to be a seperate dataframe. Can be joined to Twitter Archive data

## Assessing df_retweets_favorites

In [87]:
df_retweets_favorites.sample(10)

                tweet_id  retweet_count  favorite_count
1006  744971049620602880           2401            7149
916   752568224206688256           2056            5004
464   814638523311648768           2486           10432
1776  676916996760600576           1591            2641
1986  672160042234327040            301             751
1953  672902681409806336            417            1188
427   819015331746349057          17468               0
1401  697516214579523584            977            1837
1404  697270446429966336           1683            4257
1344  701952816642965504            913            3446

In [88]:
df_retweets_favorites.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2325 entries, 0 to 2324
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   tweet_id        2325 non-null   int64
 1   retweet_count   2325 non-null   int64
 2   favorite_count  2325 non-null   int64
dtypes: int64(3)
memory usage: 54.6 KB

##### Quality issues:
- tweet_id is stored as integer type, but won't be used for calcs, should change to object type.

##### Tidiness issue:
- No need for this data to be a seperate dataframe. Can be joined to Twitter Archive data to create one master data set

# Cleaning the Data
Now that each of the datasets have been assessed both visually and programatically, I now moved on to cleaning the data.

Before cleaning the datasets, I will first create copies of each data set:

In [121]:
df_twitter_archive_clean = df_twitter_archive.copy()
df_image_predictions_clean = df_image_predictions.copy()
df_retweets_favorites_clean = df_retweets_favorites.copy()

### Cleaning 1 - Convert timestamp to datetime in Twitter Archive

##### Define
- Change datatype of `timestamp` from object to datetime

##### Code

In [122]:
df_twitter_archive_clean.timestamp = pd.to_datetime(df_twitter_archive_clean.timestamp)

#### Test

In [123]:
df_twitter_archive_clean.timestamp.info()

<class 'pandas.core.series.Series'>
RangeIndex: 2356 entries, 0 to 2355
Series name: timestamp
Non-Null Count  Dtype
--------------  -----
2356 non-null   datetime64[ns, UTC]
dtypes: datetime64[ns, UTC](1)
memory usage: 18.5 KB

### Cleaning 2 - Change Tweet ID data type to string

#### Define
- change datatype of `tweet_id` from integer to string for each dataset

#### Code

In [124]:
df_twitter_archive_clean.tweet_id  = df_twitter_archive_clean.tweet_id.astype(str)
df_image_predictions_clean.tweet_id = df_image_predictions_clean.tweet_id.astype(str)
df_retweets_favorites_clean.tweet_id = df_retweets_favorites_clean.tweet_id.astype(str)

#### Test

In [105]:
df_twitter_archive_clean.tweet_id.info()
df_image_predictions_clean.tweet_id.info()
df_retweets_favorites_clean.tweet_id.info()

<class 'pandas.core.series.Series'>
RangeIndex: 2356 entries, 0 to 2355
Series name: tweet_id
Non-Null Count  Dtype
--------------  -----
2356 non-null   object
dtypes: object(1)
memory usage: 18.5+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 2075 entries, 0 to 2074
Series name: tweet_id
Non-Null Count  Dtype
--------------  -----
2075 non-null   object
dtypes: object(1)
memory usage: 16.3+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 2325 entries, 0 to 2324
Series name: tweet_id
Non-Null Count  Dtype
--------------  -----
2325 non-null   object
dtypes: object(1)
memory usage: 18.3+ KB

### Cleaning 3 - Remove All Retweets from Twitter Archive Data
#### Define
- Use `retweeted_status_id` to remove to exclude retweets
- Change `retweeted_status_id` to string datatype

##### Code

In [125]:
# exclude data where retweet_status_id is not null
df_twitter_archive_clean = df_twitter_archive_clean[df_twitter_archive_clean["retweeted_status_id"].isnull()]

# change type to string
df_twitter_archive_clean.retweeted_status_id = df_twitter_archive_clean.retweeted_status_id.astype(str)

##### Test

In [110]:
df_twitter_archive_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2175 entries, 0 to 2355
Data columns (total 17 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   tweet_id                    2175 non-null   object
 1   in_reply_to_status_id       78 non-null     float64
 2   in_reply_to_user_id         78 non-null     float64
 3   timestamp                   2175 non-null   datetime64[ns, UTC]
 4   source                      2175 non-null   object
 5   text                        2175 non-null   object
 6   retweeted_status_id         2175 non-null   object
 7   retweeted_status_user_id    0 non-null      float64
 8   retweeted_status_timestamp  0 non-null      object
 9   expanded_urls               2117 non-null   object
 10  rating_numerator            2175 non-null   int64
 11  rating_denominator          2175 non-null   int64
 12  name                        2175 non-null   object
 13  doggo                       2175 non-null   object
 14  floofer                     2175 non-null   object
 15  pupper                      2175 non-null   object
 16  puppo                       2175 non-null   object
dtypes: datetime64[ns, UTC](1), float64(3), int64(2), object(11)
memory usage: 305.9+ KB

## Cleaning 4 - Exclude data with missing expanded_urls
##### Define:
- Remove rows where `expanded_urls` is null

##### Code

In [126]:
df_twitter_archive_clean = df_twitter_archive_clean[df_twitter_archive_clean["expanded_urls"].notnull()]

##### Test

In [118]:
df_twitter_archive_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2117 entries, 0 to 2355
Data columns (total 17 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   tweet_id                    2117 non-null   object
 1   in_reply_to_status_id       23 non-null     float64
 2   in_reply_to_user_id         23 non-null     float64
 3   timestamp                   2117 non-null   datetime64[ns, UTC]
 4   source                      2117 non-null   object
 5   text                        2117 non-null   object
 6   retweeted_status_id         2117 non-null   object
 7   retweeted_status_user_id    0 non-null      float64
 8   retweeted_status_timestamp  0 non-null      object
 9   expanded_urls               2117 non-null   object
 10  rating_numerator            2117 non-null   int64
 11  rating_denominator          2117 non-null   int64
 12  name                        2117 non-null   object
 13  doggo                       2117 non-null   object
 14  floofer                     2117 non-null   object
 15  pupper                      2117 non-null   object
 16  puppo                       2117 non-null   object
dtypes: datetime64[ns, UTC](1), float64(3), int64(2), object(11)
memory usage: 297.7+ KB

## Cleaning 5 - Remove rows where rating_denominator does not equal 10          
##### Define
Exlude data where rating_denominator does not equal 10

###### Code

In [132]:
df_twitter_archive_clean = df_twitter_archive_clean[df_twitter_archive_clean["rating_denominator"]==10]

##### Test

In [135]:
df_twitter_archive_clean["rating_denominator"].value_counts()

10    2099
Name: rating_denominator, dtype: int64

## Cleaning 6 - Remove rows where rating_numerator is greater than 20

In [137]:
df_twitter_archive_clean["rating_numerator"].value_counts()

12      489
10      436
11      417
13      295
9       153
8        98
7        51
14       40
5        34
6        32
3        19
4        15
2         9
1         4
0         2
27        1
75        1
1776      1
26        1
420       1
Name: rating_numerator, dtype: int64

After removing values where denominator does not equal 10, there still remains numerator values where the value is greater than 20. We will assume these are incorrect / typos and so these will be removed from the data set.
##### Define
Remove rows where `rating_numerator`is greater than 20

##### Code

In [140]:
df_twitter_archive_clean = df_twitter_archive_clean[df_twitter_archive_clean["rating_numerator"] <= 20]

##### Test

In [141]:
df_twitter_archive_clean["rating_numerator"].value_counts()

12    489
10    436
11    417
13    295
9     153
8      98
7      51
14     40
5      34
6      32
3      19
4      15
2       9
1       4
0       2
Name: rating_numerator, dtype: int64

## Cleaning 7 - Cleaning Dog names
##### Define
Replace name value where the name is "None" or "a" with a Null value

##### Code

In [156]:
df_twitter_archive_clean["name"] = df_twitter_archive_clean["name"].replace("None", None)
df_twitter_archive_clean["name"] = df_twitter_archive_clean["name"].replace("a", None)

##### Test

In [157]:
df_twitter_archive_clean["name"].value_counts()

Charlie       11
Lucy          11
Cooper        10
Oliver        10
Tucker         9
              ..
Wishes         1
Rose           1
Theo           1
Fido           1
Christoper     1
Name: name, Length: 950, dtype: int64

## Cleaning 8 - Convert the 4 dog stages column to one single Dog Stage column
##### Define:
- Create a new column called dog_stage
- Populate dog_stage column with correct value
- Where there is more than one dog stage value, then concatonate values
- Where dog stage is "None" replace with Null
- Delete the columns "doggo", "floofer", "pupper", "puppo"

In [163]:
df_twitter_archive_clean.groupby(["doggo","floofer","pupper","puppo"])["tweet_id"].count().reset_index()

   doggo  floofer  pupper  puppo  tweet_id
0   None     None    None   None      1757
1   None     None    None  puppo        23
2   None     None  pupper   None       221
3   None  floofer    None   None         9
4  doggo     None    None   None        72
5  doggo     None    None  puppo         1
6  doggo     None  pupper   None        10
7  doggo  floofer    None   None         1

##### Code

In [166]:
df_twitter_archive_clean["doggo"].replace("None","",inplace=True)
df_twitter_archive_clean["floofer"].replace("None","",inplace=True)
df_twitter_archive_clean["pupper"].replace("None","",inplace=True)
df_twitter_archive_clean["puppo"].replace("None","",inplace=True)

In [175]:
df_twitter_archive_clean.groupby(["doggo","floofer","pupper","puppo"])["tweet_id"].count().reset_index()

   doggo  floofer  pupper  puppo  tweet_id
0                                     1757
1                          puppo        23
2                  pupper              221
3         floofer                        9
4  doggo                                72
5  doggo                   puppo         1
6  doggo           pupper               10
7  doggo  floofer                        1

In [180]:
# create new column called dog_stage
df_twitter_archive_clean["dog_stage"] = df_twitter_archive_clean["doggo"] + df_twitter_archive_clean["floofer"] + df_twitter_archive_clean["pupper"] + df_twitter_archive_clean["puppo"]

In [183]:
# replace empty string values with Nulls
df_twitter_archive_clean["dog_stage"].replace("", None, inplace=True)

In [185]:
# Delete previous columns
del df_twitter_archive_clean["doggo"]
del df_twitter_archive_clean["floofer"]
del df_twitter_archive_clean["pupper"]
del df_twitter_archive_clean["puppo"]

##### Test

In [184]:
# review values in new column dog_stage
df_twitter_archive_clean["dog_stage"].value_counts()

pupper          221
doggo            72
puppo            23
doggopupper      10
floofer           9
doggopuppo        1
doggofloofer      1
Name: dog_stage, dtype: int64

In [186]:
df_twitter_archive_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2094 entries, 0 to 2355
Data columns (total 14 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   tweet_id                    2094 non-null   object
 1   in_reply_to_status_id       22 non-null     float64
 2   in_reply_to_user_id         22 non-null     float64
 3   timestamp                   2094 non-null   datetime64[ns, UTC]
 4   source                      2094 non-null   object
 5   text                        2094 non-null   object
 6   retweeted_status_id         2094 non-null   object
 7   retweeted_status_user_id    0 non-null      float64
 8   retweeted_status_timestamp  0 non-null      object
 9   expanded_urls               2094 non-null   object
 10  rating_numerator            2094 non-null   int64
 11  rating_denominator          2094 non-null   int64
 12  name                        1432 non-null   object
 13  dog_stage                   337 non-null    object
dtypes: datetime64[ns, UTC](1), float64(3), int64(2), object(8)
memory usage: 245.4+ KB

## Cleaning 9 - Merge Twitter Archive Data to Image Predictions Data
##### Define
- Create a dataframe called df_master by merging the 2 dataframes df_twitter_archive_clean, df_image_predictions_clean by joining based on the tweet_id

##### Code

In [211]:
df_master = pd.merge(df_twitter_archive_clean, df_image_predictions_clean, on="tweet_id", how="left")

##### Test

In [212]:
df_master.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2094 entries, 0 to 2093
Data columns (total 25 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   tweet_id                    2094 non-null   object
 1   in_reply_to_status_id       22 non-null     float64
 2   in_reply_to_user_id         22 non-null     float64
 3   timestamp                   2094 non-null   datetime64[ns, UTC]
 4   source                      2094 non-null   object
 5   text                        2094 non-null   object
 6   retweeted_status_id         2094 non-null   object
 7   retweeted_status_user_id    0 non-null      float64
 8   retweeted_status_timestamp  0 non-null      object
 9   expanded_urls               2094 non-null   object
 10  rating_numerator            2094 non-null   int64
 11  rating_denominator          2094 non-null   int64
 12  name                        1432 non-null   object
 13  dog_stage                   337 non-null    object
 14  jpg_url                     1971 non-null   object
 15  img_num                     1971 non-null   float64
 16  p1                          1971 non-null   object
 17  p1_conf                     1971 non-null   float64
 18  p1_dog                      1971 non-null   object
 19  p2                          1971 non-null   object
 20  p2_conf                     1971 non-null   float64
 21  p2_dog                      1971 non-null   object
 22  p3                          1971 non-null   object
 23  p3_conf                     1971 non-null   float64
 24  p3_dog                      1971 non-null   object
dtypes: datetime64[ns, UTC](1), float64(7), int64(2), object(15)
memory usage: 425.3+ KB

## Cleaning 10 - Merge Likes and Retweets Data to newly created Master dataset
##### Define
Merge the dataframe df_retweets_favorites_clean to df_master using the tweet_id

##### Code

In [213]:
df_master = pd.merge(df_master, df_retweets_favorites_clean, on="tweet_id", how="left")

##### Test

In [6]:
df_master.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2094 entries, 0 to 2093
Data columns (total 22 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   tweet_id            2094 non-null   object
 1   timestamp           2094 non-null   datetime64[ns, UTC]
 2   source              2094 non-null   object
 3   text                2094 non-null   object
 4   expanded_urls       2094 non-null   object
 5   rating_numerator    2094 non-null   int64
 6   rating_denominator  2094 non-null   int64
 7   name                1432 non-null   object
 8   dog_stage           337 non-null    object
 9   jpg_url             1971 non-null   object
 10  img_num             1971 non-null   float64
 11  p1                  1971 non-null   object
 12  p1_conf             1971 non-null   float64
 13  p1_dog              1971 non-null   object
 14  p2                  1971 non-null   object
 15  p2_conf             1971 non-null   float64
 16  p2_dog              1971 non-null   object
 17  p3                  1971 non-null   object
 18  p3_conf             1971 non-null   float64
 19  p3_dog              1971 non-null   object
 20  retweet_count       2086 non-null   float64
 21  favorite_count      2086 non-null   float64
dtypes: datetime64[ns, UTC](1), float64(6), int64(2), object(13)
memory usage: 360.0+ KB

## Cleaning 11 - Remove unnecessary columns from df_master
#### Define
Remove columns:
- in_reply_to_status_id
- in_reply_to_user_id
- retweeted_status_id
- retweeted_status_user_id
- retweeted_status_timestamp

##### Code

In [215]:
cols_to_delete = ["in_reply_to_status_id","in_reply_to_user_id","retweeted_status_id","retweeted_status_user_id","retweeted_status_timestamp"]
df_master.drop(cols_to_delete, axis=1, inplace=True)

##### Test

In [216]:
df_master.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2094 entries, 0 to 2093
Data columns (total 22 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   tweet_id            2094 non-null   object
 1   timestamp           2094 non-null   datetime64[ns, UTC]
 2   source              2094 non-null   object
 3   text                2094 non-null   object
 4   expanded_urls       2094 non-null   object
 5   rating_numerator    2094 non-null   int64
 6   rating_denominator  2094 non-null   int64
 7   name                1432 non-null   object
 8   dog_stage           337 non-null    object
 9   jpg_url             1971 non-null   object
 10  img_num             1971 non-null   float64
 11  p1                  1971 non-null   object
 12  p1_conf             1971 non-null   float64
 13  p1_dog              1971 non-null   object
 14  p2                  1971 non-null   object
 15  p2_conf             1971 non-null   float64
 16  p2_dog              1971 non-null   object
 17  p3                  1971 non-null   object
 18  p3_conf             1971 non-null   float64
 19  p3_dog              1971 non-null   object
 20  retweet_count       2086 non-null   float64
 21  favorite_count      2086 non-null   float64
dtypes: datetime64[ns, UTC](1), float64(6), int64(2), object(13)
memory usage: 376.3+ KB

## Store df_master into a csv
Once the cleaning was complete I stored the final, clean dataset as a CSV file named: `twitter_archive_master.csv`

In [217]:
df_master.to_csv("twitter_archive_master.csv", index=False)